//@version=5
indicator(title='ABSM', overlay=true)

// Inputs
a = input(2, title='Key Value. \'This changes the sensitivity\'')
c = input(1, title='ATR Period')
h = input(false, title='Signals from Heikin Ashi Candles')
tma_length = input(8, title='TMA Period') // Nuevo input para TMA
ema4_length = input(4, title='EMA 4 Period') // Nuevo input para EMA 4
ema8_length = input(8, title='EMA 8 Period') // Nuevo input para EMA 8
ema21_length = input(21, title='EMA 21 Period') // Nuevo input para EMA 21
ema4_color = input(color.new(color.blue, 0), title="EMA 4 Color") // Nuevo input para el color de la EMA 4
ema8_color = input(color.new(color.red, 0), title="EMA 8 Color") // Nuevo input para el color de la EMA 8
ema21_color = input(color.new(color.green, 0), title="EMA 21 Color") // Nuevo input para el color de la EMA 21
tma_color = input(color.new(color.purple, 0), title="TMA Color") // Nuevo input para el color del TMA

// Calculating ATR
xATR = ta.atr(c)
nLoss = a * xATR

// Calculating Heikin Ashi or Regular Candles
src = h ? request.security(ticker.heikinashi(syminfo.tickerid), timeframe.period, close, lookahead=barmerge.lookahead_off) : close

// Calculating Trailing Stop
xATRTrailingStop = 0.0
iff_1 = src > nz(xATRTrailingStop[1], 0) ? src - nLoss : src + nLoss
iff_2 = src < nz(xATRTrailingStop[1], 0) and src[1] < nz(xATRTrailingStop[1], 0) ? math.min(nz(xATRTrailingStop[1]), src + nLoss) : iff_1
xATRTrailingStop := src > nz(xATRTrailingStop[1], 0) and src[1] > nz(xATRTrailingStop[1], 0) ? math.max(nz(xATRTrailingStop[1]), src - nLoss) : iff_2

// Calculating Position
pos = 0
iff_3 = src[1] > nz(xATRTrailingStop[1], 0) and src < nz(xATRTrailingStop[1], 0) ? -1 : nz(pos[1], 0)
pos := src[1] < nz(xATRTrailingStop[1], 0) and src > nz(xATRTrailingStop[1], 0) ? 1 : iff_3

// Setting Color
xcolor = pos == -1 ? color.red : pos == 1 ? color.green : color.blue

// Calculating EMAs with user-defined lengths
ema4 = ta.ema(src, ema4_length)
ema8 = ta.ema(src, ema8_length)
ema21 = ta.ema(src, ema21_length)

// Calculating Triangular Moving Average (TMA) with user-defined length
tma = ta.sma(ta.sma(src, tma_length), tma_length)

// Plotting EMAs and TMA with user-defined colors
plot(ema4, color=color.new(ema4_color, 0), title='EMA 4')
plot(ema8, color=color.new(ema8_color, 0), title='EMA 8')
plot(ema21, color=color.new(ema21_color, 0), title='EMA 21')
plot(tma, color=color.new(tma_color, 0), title='TMA')

// Calculating Buy and Sell Conditions
ema = ta.ema(src, 1)
above = ta.crossover(ema, xATRTrailingStop)
below = ta.crossover(xATRTrailingStop, ema)

compra = src > xATRTrailingStop and above
venta = src < xATRTrailingStop and below

barbuy = src > xATRTrailingStop
barsell = src < xATRTrailingStop

// Plotting Buy and Sell Signals
plotshape(compra, title='Compra', text='Compra', style=shape.labelup, location=location.belowbar, color=color.new(color.green, 0), textcolor=color.new(color.white, 0), size=size.tiny)
plotshape(venta, title='Venta', text='Venta', style=shape.labeldown, location=location.abovebar, color=color.new(color.red, 0), textcolor=color.new(color.white, 0), size=size.tiny)

// Coloring Bars
barcolor(barbuy ? color.green : na)
barcolor(barsell ? color.red : na)

// Setting up Alerts
alertcondition(compra, 'Alert Long', 'Alert Long')
alertcondition(venta, 'Alert Short', 'Alert Short')
